name: Terraform Apply

on:
  push:
    branches: [ main ]

  workflow_dispatch:
#all env
env: 
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install TerraSpace
        run: |
          sudo gem install bundler
          sudo gem install terraspace
          bundle
        
      - name: Check TerraSpace Installation
        run: terraspace setup check
        
      - name: Check az cli
        run: az version
        
      - name: az Login
        run: |
          az login --service-principal -u "$ARM_CLIENT_ID" -p "$ARM_CLIENT_SECRET" --tenant "$ARM_TENANT_ID"
          az account list
          
      - name: Plan
        run: |
          export ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID
          export ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET
          export ARM_TENANT_ID=$ARM_TENANT_ID
          export ARM_CLIENT_ID=$ARM_CLIENT_ID
          export ARM_LOCATION=canadacentral
          terraspace up bcp -auto-approve
          
